import { discretizeEntity, isClosedEntity, pointsAlmostEqual } from "./geometry";
import type {
  CamParameters,
  DrawingAnalysis,
  GCodeProgram,
  GeometryEntity,
  MachiningFeature,
  Point2,
  ToolpathMove,
  ToolpathOperation
} from "./schema";

export function buildToolpaths(analysis: DrawingAnalysis, params: CamParameters): ToolpathOperation[] {
  return analysis.features.map((feature) => buildOperation(feature, analysis.entities, params));
}

export function generateGCode(analysis: DrawingAnalysis, params: CamParameters, operations: ToolpathOperation[]): GCodeProgram {
  const warnings = validateForMachining(analysis, params, operations);
  const header = ["(Generated by KI CNC Zeichnungsanalyse MVP)", `(Source: ${analysis.fileName})`, "(Post: generic GRBL/LinuxCNC style)"];
  const setup = ["G21", "G90", "G17", `G0 Z${fmt(params.safeZMm)}`, `M3 S${Math.round(params.spindleRpm)}`];
  const operationLines = operations.flatMap((operation) => operationToGCode(operation, params));
  const footer = [`G0 Z${fmt(params.safeZMm)}`, "M5", "G0 X0 Y0", "M30"];
  const text = [...header, ...warnings.map((warning) => `(WARN: ${warning})`), ...setup, ...operationLines, ...footer].join("\n");
  return { header, setup, operations: operationLines, footer, warnings, text };
}

function buildOperation(feature: MachiningFeature, entities: GeometryEntity[], params: CamParameters): ToolpathOperation {
  const featureEntities = entities.filter((entity) => feature.geometryEntityIds.includes(entity.id));
  const warnings: string[] = [];
  if (featureEntities.length === 0) warnings.push("Feature verweist auf keine vorhandene Geometrie.");

  const depth = Math.abs(feature.depthMm || params.cutDepthMm);
  const passDepths = buildPassDepths(depth, params.stepDownMm);

  if (feature.type === "drill") {
    const holeRadius = Math.max(0.1, feature.diameterMm / 2);
    const toolRadius = Math.max(0.1, params.toolDiameterMm / 2);
    const useHelix = holeRadius > toolRadius * 1.05;
    return {
      id: `op-${feature.id}`,
      type: "drill",
      label: feature.label,
      depthMm: depth,
      warnings,
      passes: passDepths.map((zMm, index) => {
        const prevDepth = index === 0 ? 0 : passDepths[index - 1];
        return {
          zMm,
          moves: useHelix
            ? buildHelixDrillMoves(feature.center, holeRadius, toolRadius, prevDepth, zMm, params)
            : [
                { kind: "rapid", to: { x: feature.center.x, y: feature.center.y, z: params.safeZMm } },
                { kind: "linear", to: { x: feature.center.x, y: feature.center.y, z: -zMm }, feedMmMin: params.plungeRateMmMin },
                { kind: "rapid", to: { x: feature.center.x, y: feature.center.y, z: params.safeZMm } }
              ]
        };
      })
    };
  }

  const hasPath = featureEntities.some((entity) => entityStartPoint(entity) !== null);
  if (!hasPath) warnings.push("Keine Werkzeugpfadpunkte erzeugt.");
  if (feature.type !== "engrave" && featureEntities.some((entity) => !isClosedEntity(entity))) {
    warnings.push("Profil/Tasche enthält offene Geometrie.");
  }

  return {
    id: `op-${feature.id}`,
    type: feature.type,
    label: feature.label,
    depthMm: depth,
    warnings,
    passes: passDepths.map((zMm) => ({
      zMm,
      moves: entitiesToMoves(featureEntities, -zMm, params)
    }))
  };
}

function buildPassDepths(totalDepth: number, stepDown: number): number[] {
  const safeStep = Math.max(0.1, stepDown || totalDepth || 1);
  const depths: number[] = [];
  for (let depth = safeStep; depth < totalDepth; depth += safeStep) depths.push(round(depth));
  depths.push(round(totalDepth));
  return Array.from(new Set(depths));
}

function pointsToMoves(points: Point2[], z: number, params: CamParameters): ToolpathMove[] {
  if (points.length === 0) return [];
  const [first, ...rest] = points;
  return [
    { kind: "rapid", to: { ...first, z: params.safeZMm } },
    { kind: "linear", to: { ...first, z }, feedMmMin: params.plungeRateMmMin },
    ...rest.map<ToolpathMove>((point) => ({ kind: "linear", to: { ...point, z }, feedMmMin: params.feedRateMmMin })),
    { kind: "rapid", to: { ...points.at(-1)!, z: params.safeZMm } }
  ];
}

function entitiesToMoves(entities: GeometryEntity[], z: number, params: CamParameters): ToolpathMove[] {
  const moves: ToolpathMove[] = [];
  let current: Point2 | null = null;

  for (const entity of entities) {
    const start = entityStartPoint(entity);
    if (!start) continue;
    if (!current || !pointsAlmostEqual(current, start)) {
      if (current) moves.push({ kind: "rapid", to: { ...current, z: params.safeZMm } });
      moves.push({ kind: "rapid", to: { ...start, z: params.safeZMm } });
      moves.push({ kind: "linear", to: { ...start, z }, feedMmMin: params.plungeRateMmMin });
    }
    moves.push(...entityCutMoves(entity, z, params));
    current = entityEndPoint(entity);
  }

  if (current) moves.push({ kind: "rapid", to: { ...current, z: params.safeZMm } });
  return moves;
}

function entityCutMoves(entity: GeometryEntity, z: number, params: CamParameters): ToolpathMove[] {
  if (entity.type === "circle") {
    const start = { x: entity.center.x + entity.radius, y: entity.center.y };
    const opposite = { x: entity.center.x - entity.radius, y: entity.center.y };
    return [
      { kind: "arc", to: { ...opposite, z }, centerOffset: { x: -entity.radius, y: 0 }, clockwise: true, feedMmMin: params.feedRateMmMin },
      { kind: "arc", to: { ...start, z }, centerOffset: { x: entity.radius, y: 0 }, clockwise: true, feedMmMin: params.feedRateMmMin }
    ];
  }

  if (entity.type === "arc") {
    const start = arcPoint(entity, entity.startAngleDeg);
    const end = arcPoint(entity, entity.endAngleDeg);
    const clockwise = isArcClockwise(entity);
    return [
      {
        kind: "arc",
        to: { ...end, z },
        centerOffset: { x: entity.center.x - start.x, y: entity.center.y - start.y },
        clockwise,
        feedMmMin: params.feedRateMmMin
      }
    ];
  }

  const points = discretizeEntity(entity);
  return points.slice(1).map<ToolpathMove>((point) => ({ kind: "linear", to: { ...point, z }, feedMmMin: params.feedRateMmMin }));
}

function entityStartPoint(entity: GeometryEntity): Point2 | null {
  if (entity.type === "line") return entity.start;
  if (entity.type === "circle") return { x: entity.center.x + entity.radius, y: entity.center.y };
  if (entity.type === "arc") return arcPoint(entity, entity.startAngleDeg);
  return entity.points[0] ?? null;
}

function entityEndPoint(entity: GeometryEntity): Point2 {
  if (entity.type === "line") return entity.end;
  if (entity.type === "circle") return { x: entity.center.x + entity.radius, y: entity.center.y };
  if (entity.type === "arc") return arcPoint(entity, entity.endAngleDeg);
  return entity.closed ? (entity.points[0] ?? { x: 0, y: 0 }) : (entity.points.at(-1) ?? { x: 0, y: 0 });
}

function arcPoint(entity: Extract<GeometryEntity, { type: "arc" }>, angleDeg: number): Point2 {
  const angle = (angleDeg * Math.PI) / 180;
  return {
    x: entity.center.x + Math.cos(angle) * entity.radius,
    y: entity.center.y + Math.sin(angle) * entity.radius
  };
}

function isArcClockwise(entity: Extract<GeometryEntity, { type: "arc" }>): boolean {
  const delta = normalizeSignedAngle(entity.endAngleDeg - entity.startAngleDeg);
  return delta < 0;
}

function normalizeSignedAngle(angleDeg: number): number {
  let normalized = angleDeg % 360;
  if (normalized > 180) normalized -= 360;
  if (normalized <= -180) normalized += 360;
  return normalized;
}

function buildHelixDrillMoves(
  center: Point2,
  holeRadius: number,
  toolRadius: number,
  prevDepth: number,
  nextDepth: number,
  params: CamParameters
): ToolpathMove[] {
  const pathRadius = Math.max(0.1, holeRadius - toolRadius);
  const start = { x: center.x + pathRadius, y: center.y };
  const prevZ = -prevDepth;
  const targetZ = -nextDepth;
  const midZ = prevZ + (targetZ - prevZ) / 2;

  return [
    { kind: "rapid", to: { ...start, z: params.safeZMm } },
    { kind: "linear", to: { ...start, z: prevZ }, feedMmMin: params.plungeRateMmMin },
    { kind: "arc", to: { x: center.x - pathRadius, y: center.y, z: midZ }, centerOffset: { x: -pathRadius, y: 0 }, clockwise: true, feedMmMin: params.feedRateMmMin },
    { kind: "arc", to: { ...start, z: targetZ }, centerOffset: { x: pathRadius, y: 0 }, clockwise: true, feedMmMin: params.feedRateMmMin },
    { kind: "rapid", to: { ...start, z: params.safeZMm } }
  ];
}

function operationToGCode(operation: ToolpathOperation, params: CamParameters): string[] {
  return [
    "",
    `(Operation: ${operation.label})`,
    ...operation.warnings.map((warning) => `(WARN: ${warning})`),
    ...operation.passes.flatMap((pass) => [`(Pass Z-${fmt(pass.zMm)})`, ...pass.moves.map((move) => moveToGCode(move, params))])
  ];
}

function moveToGCode(move: ToolpathMove, params: CamParameters): string {
  if (move.kind === "rapid") return `G0 X${fmt(move.to.x)} Y${fmt(move.to.y)} Z${fmt(move.to.z)}`;
  if (move.kind === "linear") {
    const feed = move.feedMmMin ?? params.feedRateMmMin;
    return `G1 X${fmt(move.to.x)} Y${fmt(move.to.y)} Z${fmt(move.to.z)} F${Math.round(feed)}`;
  }
  const command = move.clockwise ? "G2" : "G3";
  const feed = move.feedMmMin ?? params.feedRateMmMin;
  return `${command} X${fmt(move.to.x)} Y${fmt(move.to.y)} Z${fmt(move.to.z)} I${fmt(move.centerOffset.x)} J${fmt(move.centerOffset.y)} F${Math.round(feed)}`;
}

function validateForMachining(analysis: DrawingAnalysis, params: CamParameters, operations: ToolpathOperation[]): string[] {
  const warnings = [...analysis.warnings, ...operations.flatMap((operation) => operation.warnings)];
  if (analysis.units === "unknown") warnings.push("Einheiten unbekannt: G-Code wird als Millimeter ausgegeben.");
  if (params.toolDiameterMm <= 0) warnings.push("Werkzeugdurchmesser muss positiv sein.");
  if (params.cutDepthMm <= 0) warnings.push("Schnitttiefe muss positiv sein.");
  if (params.stepDownMm > params.cutDepthMm) warnings.push("Zustellung ist größer als Schnitttiefe.");
  if (params.feedRateMmMin <= 0 || params.plungeRateMmMin <= 0) warnings.push("Vorschubwerte müssen positiv sein.");
  if (params.stockThicknessMm < params.cutDepthMm) warnings.push("Schnitttiefe überschreitet Materialstärke.");
  return Array.from(new Set(warnings));
}

function fmt(value: number): string {
  return round(value).toFixed(3).replace(/\.?0+$/, "");
}

function round(value: number): number {
  return Math.round(value * 1000) / 1000;
}
